server:
  port: 8080
  servlet:
    context-path: /HealthCare

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HealthCareDB
    username: root
    password: tiendat07022003
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  signerKey: "K1YJD9Mt3V3wklqFpuYQXZhKSMdh6UZyLBb/nvXKBk1Lw3yXtRYTcpLqwOa8ACsc"
  refreshable-duration: 360000  # tính bằng giây
  valid-duration: 3600 # tính bằng giây
